Разметка главной страницы
htmlacademy-adaptive/53806-sedona-21 pull request #2
Opened 2020-11-13 19:37 UTC by thatverygeorge

2020-11-14 20:50 UTC, dean992008 requested changes

2020-11-14 20:50 UTC, dean992008 commented on source/index.html
> +<html class="page" lang="ru">
Не нужно давать класс на html и body.

2020-11-14 20:50 UTC, dean992008 commented on source/index.html
> +
Нужно поудалять лишнее пустые строки.

2020-11-14 20:50 UTC, dean992008 commented on source/index.html
> +        <li class="reasons__item reasons__item--with-image reasons__item--with-features">
Карточки (каждый li) я бы делал отдельным элементом

2020-11-14 20:50 UTC, dean992008 commented on source/index.html
> +          <p class="reasons__number">— №1 —</p>
Полоски это псевдоэлемент.

2020-11-14 20:50 UTC, dean992008 commented on source/index.html
> +            <ul class="features__list">
Желье, Сувениры и Еда я бы перенес в 6 li, а потом перенес с помощью CSS

2020-11-14 20:50 UTC, dean992008 commented on source/index.html
> +      <iframe
Iframe пока не нужно делать, сы карту сделаем с помощью CSS

2020-11-15 07:50 UTC, thatverygeorge commented on source/index.html
> +      <iframe
Уберу. Но любопытно узнать, как делается карта на CSS в двух словах?

2020-11-15 07:50 UTC, thatverygeorge commented on source/index.html
> +        <li class="reasons__item reasons__item--with-image reasons__item--with-features">
Не до конца понял, что ты имеешь в виду. Примиксовать модификатор вроде "reasons__item reasons__item--real-city"?

2020-11-16 13:54 UTC, dean992008 commented on source/index.html
> +        <li class="reasons__item reasons__item--with-image reasons__item--with-features">
Нет, это виде сделать Микс: https://ru.bem.info/methodology/quick-start/#%D0%BC%D0%B8%D0%BA%D1%81
Тоесть li нужно делать блоком, со своими элментами, при этом 2 классом добавить элемент от родителя.

2020-11-16 13:56 UTC, dean992008 commented on source/index.html
> +      <iframe
Тут не коректно написал, не CSS, а JS: 
 - https://developers.google.com/maps/documentation/javascript/overview
 - https://yandex.ru/dev/maps/jsapi/doc/2.1/quick-start/index.html/?from=techmapsmain

2020-11-16 19:11 UTC, merged